services:
  - type: worker
    name: mexc_futures_bot
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MEXC_API_KEY
        sync: false
      - key: MEXC_SECRET_KEY
        sync: false
      - key: CHAT_ID
        sync: false
